let yourName = 'Євген';
let surname = 'Заяц';
let group = 583;
let birthYear = 1984;
let married = true;
let nll = null;
let undef = undefined;
console.log(typeof(group));
console.log(typeof(birthYear));
console.log(typeof(married));
console.log(typeof(yourName));
console.log(typeof(surname));
console.log(typeof(nll));
console.log(typeof(undef));
